// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmqw07RdFjsM1Tgg_u5qfGRAEX8UPE8F4',
    appId: '1:90963734221:ios:26923713eae10dcc56c384',
    messagingSenderId: '90963734221',
    projectId: 'whatsbackup-ec952',
    storageBucket: 'whatsbackup-ec952.firebasestorage.app',
    iosBundleId: 'co.dewaal.whatsappArchiveViewer',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV5cw3b0F3bimlrtvGrwvq9Gkjwx_nqXY',
    appId: '1:90963734221:android:7737f81770c6193256c384',
    messagingSenderId: '90963734221',
    projectId: 'whatsbackup-ec952',
    storageBucket: 'whatsbackup-ec952.firebasestorage.app',
  );

}